version: '3.9'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'cursojsfprimefaces_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
